name: golden_screenshot
description: Utilities to automate screenshot generation using Flutter's golden tests.
version: 3.1.4
repository: https://github.com/adil192/golden_screenshot

topics:
  - ui
  - testing
  - screenshot

environment:
  sdk: ^3.0.0
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_test:
    sdk: flutter
  golden_toolkit: ^0.15.0
  matcher: ^0.12.16+1
  path: ^1.9.0
  web: ^1.1.0

dev_dependencies:
  flutter_lints: ^5.0.0

flutter:
  assets:
    - assets/topbars/
